name: Continuous Integration

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.2.0
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm test
